Adding support for squash: interface.
go-viper/mapstructure pull request #17
Opened 2024-04-01 16:01 UTC by m1k1o

Porting the upstream PR https://github.com/mitchellh/mapstructure/pull/325 that fixes the upstream issue https://github.com/mitchellh/mapstructure/issues/186.

2024-08-11 22:07 UTC, sagikazarmark requested changes
@m1k1o thanks for the contribution!

Would you mind fixing the lint error?

Thanks!

2024-08-12 10:08 UTC, m1k1o commented
> @m1k1o thanks for the contribution!
> 
> Would you mind fixing the lint error?
> 
> Thanks!

Fixed and resolved merge conflist with main branch.

2024-08-12 11:57 UTC, sagikazarmark approved these changes

2024-08-12 11:58 UTC, sagikazarmark commented
Thanks!

2024-08-12 11:58 UTC, merged